### ISSUE TITLE
Deadlock beim NodeCrawler

### ISSUE THREAD

**Issue by lSoleyl** [lSoleyl/ttvp#5]
Wenn ich zwischen Laptop und PC versuche die Anwendung zu starten, dann kommt es zu einem Deadlock aufgrund der beiden Node-Crawler.

Beide blockieren in [findSuccessor()](https://github.com/lSoleyl/ttvp/blob/master/src/de/haw/ttvp/gamelogic/NodeCrawler.java#L33) und es passiert auch sonst nichts. (Es kommt kein einziges retrieve() an, obwohl der Knoten, der beginnt im Log bereits ein Ziel gefunden hat, auf das er schießt. Somit konnte sein Node-Crawler zumindest einen Knoten korrekt entdecken(und beim nächsten blockiert er dann), ansonsten würde die Strategie kein Ziel liefern). Der [retrieve()](https://github.com/lSoleyl/ttvp/blob/master/src/de/haw/ttvp/gamelogic/TargetSelection.java#L36) Aufruf blockiert dann auch beim schießenden Knoten ewig.

Im Debugger sehe ich, dass der NodeCrawler und 10 ExecutionInvocation-Threads auf das Ergebnis von findSuccessors() warten, nur nie eine Antwort erhalten. (Das passiert auch, wenn ich nach jedem findSuccessor() eine Sekunde warte, damit nicht ganz so viele Anfragen auf einmal gesendet werden)

Ich hab bereits versucht, den Crawler von einem anderen Thread aus nach einem zufälligen Timeout zu interrupten, aber er lässt sich nicht aufwecken, was mich schon etwas wundert.

Das Problem gibts auch nur, wenn ich es über's Netzwerk teste und auch nur, wenn beide den Crawler an haben... schalte ich den Crawler bei einem Knoten ab, dann blockiert nichts mehr. 

---

Meine Vermutung bisher ist, dass sich eine dämliche Abfolge von findSuccessor() und retrive() blockiert, denn beide synchronisieren sich später über das gleiche Objekt, wenn sie auf Ergebnisse warten... Aber genaueres weiß ich bisher auch nicht.

**Comment by lSoleyl** [comment]
Okay, mit dem letzten Commit kommt es nicht mehr zu einem Deadlock am Anfang (zumindest bei 2 Knoten), jedoch bekomme ich jedes mal den folgenden Fehler (sobald der zweite Knoten zurückschießt) mit dem ich momentan noch nichts anfangen kann... naja mal sehen

```
9937 [InvocationExecution-Thread-11] FATAL de.uniba.wiai.lspi.chord.service.impl.NodeImpl  - The rare situation has occured at time 1421354711278, id to look up=71 85 F3 75 A9 1A DA 4A AC 29 77 51 F5 7B 8A C2 73 90 F6 EB , id of local node=C0 73 47 8F 49 A7 63 FA 0C 6E F5 7C B1 FB 38 13 A2 C0 8E DF , id of predecessor=A4 EE 77 F2 59 76 2E 30 87 F4 42 2C C7 03 E4 D4 2C 0F 89 00 
9938 [InvocationExecution-Thread-12] FATAL de.uniba.wiai.lspi.chord.service.impl.NodeImpl  - The rare situation has occured at time 1421354711279, id to look up=71 85 F3 75 A9 1A DA 4A AC 29 77 51 F5 7B 8A C2 73 90 F6 EB , id of local node=C0 73 47 8F 49 A7 63 FA 0C 6E F5 7C B1 FB 38 13 A2 C0 8E DF , id of predecessor=A4 EE 77 F2 59 76 2E 30 87 F4 42 2C C7 03 E4 D4 2C 0F 89 00 
9942 [InvocationExecution-Thread-13] FATAL de.uniba.wiai.lspi.chord.service.impl.NodeImpl  - The rare situation has occured at time 1421354711282, id to look up=71 85 F3 75 A9 1A DA 4A AC 29 77 51 F5 7B 8A C2 73 90 F6 EB , id of local node=C0 73 47 8F 49 A7 63 FA 0C 6E F5 7C B1 FB 38 13 A2 C0 8E DF , id of predecessor=A4 EE 77 F2 59 76 2E 30 87 F4 42 2C C7 03 E4 D4 2C 0F 89 00 
9943 [InvocationExecution-Thread-5] FATAL de.uniba.wiai.lspi.chord.service.impl.NodeImpl  - The rare situation has occured at time 1421354711284, id to look up=71 85 F3 75 A9 1A DA 4A AC 29 77 51 F5 7B 8A C2 73 90 F6 EB , id of local node=C0 73 47 8F 49 A7 63 FA 0C 6E F5 7C B1 FB 38 13 A2 C0 8E DF , id of predecessor=A4 EE 77 F2 59 76 2E 30 87 F4 42 2C C7 03 E4 D4 2C 0F 89 00 
9947 [InvocationExecution-Thread-14] FATAL de.uniba.wiai.lspi.chord.service.impl.NodeImpl  - The rare situation has occured at time 1421354711288, id to look up=71 85 F3 75 A9 1A DA 4A AC 29 77 51 F5 7B 8A C2 73 90 F6 EB , id of local node=C0 73 47 8F 49 A7 63 FA 0C 6E F5 7C B1 FB 38 13 A2 C0 8E DF , id of predecessor=A4 EE 77 F2 59 76 2E 30 87 F4 42 2C C7 03 E4 D4 2C 0F 89 00 
9949 [InvocationExecution-Thread-6] FATAL de.uniba.wiai.lspi.chord.service.impl.NodeImpl  - The rare situation has occured at time 1421354711289, id to look up=71 85 F3 75 A9 1A DA 4A AC 29 77 51 F5 7B 8A C2 73 90 F6 EB , id of local node=C0 73 47 8F 49 A7 63 FA 0C 6E F5 7C B1 FB 38 13 A2 C0 8E DF , id of predecessor=A4 EE 77 F2 59 76 2E 30 87 F4 42 2C C7 03 E4 D4 2C 0F 89 00 
9950 [InvocationExecution-Thread-9] FATAL de.uniba.wiai.lspi.chord.service.impl.NodeImpl  - The rare situation has occured at time 1421354711291, id to look up=71 85 F3 75 A9 1A DA 4A AC 29 77 51 F5 7B 8A C2 73 90 F6 EB , id of local node=C0 73 47 8F 49 A7 63 FA 0C 6E F5 7C B1 FB 38 13 A2 C0 8E DF , id of predecessor=A4 EE 77 F2 59 76 2E 30 87 F4 42 2C C7 03 E4 D4 2C 0F 89 00 
9952 [InvocationExecution-Thread-7] FATAL de.uniba.wiai.lspi.chord.service.impl.NodeImpl  - The rare situation has occured at time 1421354711292, id to look up=71 85 F3 75 A9 1A DA 4A AC 29 77 51 F5 7B 8A C2 73 90 F6 EB , id of local node=C0 73 47 8F 49 A7 63 FA 0C 6E F5 7C B1 FB 38 13 A2 C0 8E DF , id of predecessor=A4 EE 77 F2 59 76 2E 30 87 F4 42 2C C7 03 E4 D4 2C 0F 89 00 
9957 [InvocationExecution-Thread-10] FATAL de.uniba.wiai.lspi.chord.service.impl.NodeImpl  - The rare situation has occured at time 1421354711298, id to look up=71 85 F3 75 A9 1A DA 4A AC 29 77 51 F5 7B 8A C2 73 90 F6 EB , id of local node=C0 73 47 8F 49 A7 63 FA 0C 6E F5 7C B1 FB 38 13 A2 C0 8E DF , id of predecessor=A4 EE 77 F2 59 76 2E 30 87 F4 42 2C C7 03 E4 D4 2C 0F 89 00 
9961 [InvocationExecution-Thread-8] FATAL de.uniba.wiai.lspi.chord.service.impl.NodeImpl  - The rare situation has occured at time 1421354711302, id to look up=71 85 F3 75 A9 1A DA 4A AC 29 77 51 F5 7B 8A C2 73 90 F6 EB , id of local node=C0 73 47 8F 49 A7 63 FA 0C 6E F5 7C B1 FB 38 13 A2 C0 8E DF , id of predecessor=A4 EE 77 F2 59 76 2E 30 87 F4 42 2C C7 03 E4 D4 2C 0F 89 00 
```

Achja und bei 3 Knoten (2 davon auf der gleichen Machine) habe ich das Problem, dass das Chord-Netz gar nicht erst aufgebaut werden kann.... Starte ich alle 3 Knoten auf meinem PC, dann läuft alles wunderbar.
Ich hoffe, dass es nur die Firewall ist, die die Verbindung abblockt, (Es kommt auch im Log immer eine IOException[Connection refused], würde also passen... andererseits kommt die Verbindung bei 2 Knoten ja problemlos zustande)

**Comment by pasndrp** [comment]
Der Fehler scheint darauf hinzuweisen, dass ein neuer Node auftritt, welcher die IDs verwaltet, für die eigentlich der erwartete Predecessor zuständig war:

```
// Possible, but rare situation: a new node has joined which now is
// responsible for the id!
                if (this.references.getPredecessor() != null
                                && !id.isInInterval(this.references.getPredecessor()
                                                .getNodeID(), this.nodeID)) {
                        this.logger.fatal("The rare situation has occured at time "
                                        + System.currentTimeMillis() + ", id to look up=" + id
                                        + ", id of local node=" + this.nodeID
                                        + ", id of predecessor="
                                        + this.references.getPredecessor().getNodeID());
                        return this.references.getPredecessor().retrieveEntries(id);
                }
```

Bedeutet das vielleicht, dass Chord nicht auf allen Nodes fertig initialisiert ist, wenn das Spiel gestartet wird?

**Comment by lSoleyl** [comment]
Hmm nee, es kam noch nichtmal zum Start des Spiels. Aber anscheinend wurde die gleiche ID doppelt vergeben.

Ich müsste mir mal angucken, wie die IDs generiert werden, ich dachte eig. dass der Port dabei eine Rolle spielt und hab versucht, den zu variieren, aber das hat nicht geholfen. Ich guck mal, ob ich morgen etwas dazu finde.

**Comment by lSoleyl** [comment]
Ok, nachdem ich den Aufbau des Netzwerks nochmal etwas nachvollzogen habe, bin ich auf folgendes Stück Code gestoßen:
```java
public void join(URL bootstrapURL, int port) throws Exception {
...
try {
                        //determine how to obtain ip-address on linux system. see bug 1510537. sven
			String host = java.net.InetAddress.getLocalHost().getHostAddress();
```

Also hab ich auf meinem Laptop das ganze unter Windows gestartet und der Fehler war weg und das Spiel lief durch.

_________

Der andere Fehler, dass ich 3 Knoten nicht verbinden konnte lag daran, dass die ID aus dem Host(IP) und dem lokalen Port gebildet wird. Anscheinend wird aber nicht die LAN-IP genommen, sondern 127.0.0.1 und dann muss der Port unterschiedlich sein, damit die ID nicht identisch ist.
Wenn also beide clients mit `-lport ###` einen unterschiedlichen Port zugewiesen bekommen, dann klappts auch mit 3 Knoten im LAN.
